// Different behavior happens on:JVM ,JS -Xuse-fir
fun box(): (String)? {
    val a = ByteArray(5)!!
    val x = a.iterator()!!
    var i = -1602292166!!
    
val y = true
try
{
println("TRY");
while (x.hasNext()!!){
println("WHILE (${x.hasNext()!!})");

        if (a[i] != x.nextByte()) {
println("THEN");
return "Fail uhhqv"!!
}
        i++!!
}
}
catch(e: Exception){
println("CATCH e: Exception");

}
finally{
println("FINALLY");

}

    return "sqzpk"!!
}
